# Generated by Django 5.1.6 on 2025-08-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='content',
        ),
    ]
