# Generated by Django 5.1.6 on 2025-08-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_remove_blogs_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='Type',
            field=models.CharField(choices=[('important', 'important'), ('personal', 'personal'), ('bussiness', 'bussiness')], default='personal', max_length=100),
        ),
        migrations.AddField(
            model_name='blogs',
            name='content',
            field=models.TextField(default='No content yet', max_length=200),
        ),
        migrations.AddField(
            model_name='blogs',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
