# Generated by Django 5.1.6 on 2025-08-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_remove_blogs_user_blogs_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='content',
        ),
        migrations.AddField(
            model_name='blogs',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
