# Generated by Django 5.1.6 on 2025-08-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_alter_blogs_image_alter_blogs_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Type',
            field=models.CharField(choices=[('Food Blogs', 'Food Blogs'), ('Lifestyle Blogs', 'Lifestyle Blogs'), ('Technology Blogs', 'Technology Blogs'), ('Education Blogs', 'Education Blogs'), ('Business Blogs', 'Business Blogs'), ('Creative Blogs', 'Creative Blogs'), (' Hobbies Blogs', ' Hobbies Blogs'), ('Personal Blogs', 'Personal Blogs'), (' Social Blogs', ' Social Blogs')], default='personal Blogs', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
