# Generated by Django 5.1.6 on 2025-08-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_alter_blogs_type_alter_blogs_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Type',
            field=models.CharField(choices=[('Food Blogs', 'Food Blogs'), ('Lifestyle Blogs', 'Lifestyle Blogs'), ('Technology Blogs', 'Technology Blogs'), ('Education Blogs', 'Education Blogs'), ('Business Blogs', 'Business Blogs'), ('Creative Blogs', 'Creative Blogs'), (' Hobbies Blogs', ' Hobbies Blogs'), ('Personal Blogs', 'Personal Blogs'), (' Social Blogs', ' Social Blogs')], default='Personal Blogs', max_length=100),
        ),
    ]
