# Generated by Django 5.1.6 on 2025-08-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_alter_blogs_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='Description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Type',
            field=models.CharField(choices=[('Food Blogs', 'Food Blogs'), ('Lifestyle Blogs', 'Lifestyle Blogs'), ('Technology Blogs', 'Technology Blogs'), ('Education Blogs', 'Education Blogs'), ('Business Blogs', 'Business Blogs'), ('Creative Blogs', 'Creative Blogs'), ('Hobbies Blogs', 'Hobbies Blogs'), ('Personal Blogs', 'Personal Blogs'), ('Social Blogs', 'Social Blogs')], default='Personal Blogs', max_length=100),
        ),
    ]
